language: python
sudo: false
addons:
    apt:
        packages:
            - libfftw3-dev 
            - libhdf5-serial-dev 
            - liblapack-dev 
            - gfortran 
            - libgsl0-dev
cache:
  directories:
    - $HOME/.ccache
before_install:
  - "./tools/install_travis.sh"
install: "echo 'already instaled'"
script: "source $TRAVIS_BUILD_DIR/source;"
